### PR TITLE
📹Added support for rgb8 next to bgr8

### PR DESCRIPTION
**Pull request by rmeertens**
Hey Dustin, 

When playing around with the usb_cam package I noticed I couldn't run inference as the only accepted type in the imageconverter was bgr8. Luckily there is a cudaRGB8ToRGBA32 function available which would support my webcam without awkward conversions :)

### CODE REVIEW

**Comment by rmeertens** [comment]
Any updates on this pull request?

**Comment by rmeertens** [comment]
Hey @dusty-nv , got any time to approve this pull request?

**Comment by dusty-nv** [comment]
Sorry for the delay, @rmeertens - just merged this.  Thank you for the PR.

**Comment by rmeertens** [comment]
Awesome, thanks! 😊

**Pull request merged**
